# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_web', '0007_carmodels_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodels',
            old_name='value',
            new_name='make_value',
        ),
        migrations.AddField(
            model_name='carmodels',
            name='model_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
